# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKJqSDqP4V-_jSWVH-c1SDSiVr7dh_MA
"""

import requests
#import os
from datetime import datetime

api_key = 'bf3c1dde26cc1c48442267d418d03cfb'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

#storing in file data.txt
file1 = open('data.txt', 'w')
file1.write("Current temperature is: {:.2f} deg C".format(temp_city))
print(temp_city, file=file1)
print(weather_desc,file=file1)
print(hmdt,file=file1)
print(wind_spd,file=file1)


file1. close()

"""# New section"""